apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    app.kubernetes.io/name: nginx-test
spec:
  nodeName: k8s-master
  containers:
  - name: nginx-test
    image: nginx
    ports:
      - containerPort: 80
        name: nginx-test
