apiVersion: v1
kind: Pod
metadata:
  name: busybox-test
  labels:
    app.kubernetes.io/name: busybox-test
spec:
  nodeName: training-k8s-master
  containers:
  - name: busybox-test
    image: busybox
    command: ["sleep", "infinity"]
