apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app.kubernetes.io/name: proxy2
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
        name: http-web-svc
