apiVersion: v1
kind: Pod
metadata:
  name: web2
  labels:
    app: web-app  # Common label
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: web2-html-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: web2-html-volume
      configMap:
        name: web2-html
